#!/bin/sh
export PATH="/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
export NVARCH="${NVARCH:-"x86_64"}"
export NVIDIA_REQUIRE_CUDA="${NVIDIA_REQUIRE_CUDA:-"cuda>=11.1 brand=tesla,driver>=418,driver<419 brand=tesla,driver>=450,driver<451"}"
export NV_CUDA_CUDART_VERSION="${NV_CUDA_CUDART_VERSION:-"11.1.74-1"}"
export NV_CUDA_COMPAT_PACKAGE="${NV_CUDA_COMPAT_PACKAGE:-"cuda-compat-11-1"}"
export CUDA_VERSION="${CUDA_VERSION:-"11.1.1"}"
export LD_LIBRARY_PATH="${LD_LIBRARY_PATH:-"/usr/local/nvidia/lib:/usr/local/nvidia/lib64"}"
export NVIDIA_VISIBLE_DEVICES="${NVIDIA_VISIBLE_DEVICES:-"all"}"
export NVIDIA_DRIVER_CAPABILITIES="${NVIDIA_DRIVER_CAPABILITIES:-"compute,utility"}"
export NV_CUDA_LIB_VERSION="${NV_CUDA_LIB_VERSION:-"11.1.1-1"}"
export NV_NVTX_VERSION="${NV_NVTX_VERSION:-"11.1.74-1"}"
export NV_LIBNPP_VERSION="${NV_LIBNPP_VERSION:-"11.1.2.301-1"}"
export NV_LIBNPP_PACKAGE="${NV_LIBNPP_PACKAGE:-"libnpp-11-1=11.1.2.301-1"}"
export NV_LIBCUSPARSE_VERSION="${NV_LIBCUSPARSE_VERSION:-"11.3.0.10-1"}"
export NV_LIBCUBLAS_PACKAGE_NAME="${NV_LIBCUBLAS_PACKAGE_NAME:-"libcublas-11-1"}"
export NV_LIBCUBLAS_VERSION="${NV_LIBCUBLAS_VERSION:-"11.3.0.106-1"}"
export NV_LIBCUBLAS_PACKAGE="${NV_LIBCUBLAS_PACKAGE:-"libcublas-11-1=11.3.0.106-1"}"
export NV_LIBNCCL_PACKAGE_NAME="${NV_LIBNCCL_PACKAGE_NAME:-"libnccl2"}"
export NV_LIBNCCL_PACKAGE_VERSION="${NV_LIBNCCL_PACKAGE_VERSION:-"2.8.4-1"}"
export NCCL_VERSION="${NCCL_VERSION:-"2.8.4-1"}"
export NV_LIBNCCL_PACKAGE="${NV_LIBNCCL_PACKAGE:-"libnccl2=2.8.4-1+cuda11.1"}"
export NV_CUDNN_VERSION="${NV_CUDNN_VERSION:-"8.0.5.39"}"
export NV_CUDNN_PACKAGE_NAME="${NV_CUDNN_PACKAGE_NAME:-"libcudnn8"}"
export NV_CUDNN_PACKAGE="${NV_CUDNN_PACKAGE:-"libcudnn8=8.0.5.39-1+cuda11.1"}"
